INSERT INTO CURRENCY (CURRENCY_ID, CODE, NAME, SYMBOL) VALUES
(1, 'USD', 'United States Dollar', '$'),
(2, 'EUR', 'Euro', '€'),
(3, 'PEN', 'Peruvian Sol', 'S/.'),
(4, 'GBP', 'British Pound', '£'),
(5, 'CAD', 'Canadian Dollar', 'C$'),
(6, 'CNY', 'Chinese Yuan', '¥'),
(7, 'MXN', 'Mexican Peso', '$'),
(8, 'JPY', 'Japanese Yen', '¥'),
(9, 'ARS', 'Argentine Peso', '$'),
(10, 'COP', 'Colombian Peso', '$');

INSERT INTO EXCHANGE_RATE (FROM_CURRENCY_ID, TO_CURRENCY_ID, RATE, DATE_ADDED, DATE_MODIFIED) VALUES
(1, 2, 0.92, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 1, 1.09, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 3, 3.74, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 1, 0.27, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 3, 4.09, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 2, 0.24, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 4, 0.21, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 5, 0.36, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 6, 1.90, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 7, 4.59, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 8, 39.77, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 9, 95.16, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 10, 1089.06, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 3, 4.68, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 3, 2.72, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 3, 0.52, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, 3, 0.21, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(8, 3, 0.02, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9, 3, 0.01, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10, 3, 0.0009, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO USERS (USERNAME, PASSWORD) VALUES
('kattymmc', '$2a$10$ZtRUJMjsPlJlrXIjuCAHO.ayKLcbmiykTfzLOHZN8zqTH5NJSUZi6');